### ISSUE TITLE
char not found at launch

### ISSUE THREAD

**Issue by Reeeeeemi** [myowenthings/Nexus-v117#3]
**Thanks for your new commit.
After creating a database and import your sql script. I can finally launch the server with an exception:**

Login Server is listening on port 8484
Channel 1 is listening on port 7575
Channel 2 is listening on port 7576
Channel 3 is listening on port 7577
Channel 4 is listening on port 7578
Cash Shop Server is listening on port 8600.
Exception in thread "main" java.lang.RuntimeException: Loading the Char Failed (char not found)
        at client.MapleCharacter.loadCharFromDB(MapleCharacter.java:536)
        at client.MapleCharacter.loadCharFromDB(MapleCharacter.java:516)
        at server.Start.run(Start.java:186)
        at server.Start.main(Start.java:46)

**I just login and play around for few seconds, then my character cannot revive in the second mission, after I ate that apple. Then I lost connection. Is it related to the wz files?**

**There is the log,**
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'nexus117.battlelog' doesn't exist
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
        at com.mysql.jdbc.Util.getInstance(Util.java:384)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1054)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3562)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3494)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1960)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2114)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2696)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2105)
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2264)
        at client.MapleCharacter.loadCharFromDB(MapleCharacter.java:949)
        at client.MapleCharacter.loadCharFromDB(MapleCharacter.java:516)
        at handling.channel.handler.InterServerHandler.Loggedin(InterServerHandler.java:162)
        at handling.MapleServerHandler.handlePacket(MapleServerHandler.java:336)
        at handling.MapleServerHandler.messageReceived(MapleServerHandler.java:1241)
        at org.apache.mina.common.support.AbstractIoFilterChain$TailFilter.messageReceived(AbstractIoFilterChain.java:570)
        at org.apache.mina.common.support.AbstractIoFilterChain.callNextMessageReceived(AbstractIoFilterChain.java:299)
        at org.apache.mina.common.support.AbstractIoFilterChain.access$1100(AbstractIoFilterChain.java:53)
        at org.apache.mina.common.support.AbstractIoFilterChain$EntryImpl$1.messageReceived(AbstractIoFilterChain.java:648)
        at org.apache.mina.filter.codec.support.SimpleProtocolDecoderOutput.flush(SimpleProtocolDecoderOutput.java:58)
        at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:180)
        at org.apache.mina.common.support.AbstractIoFilterChain.callNextMessageReceived(AbstractIoFilterChain.java:299)
        at org.apache.mina.common.support.AbstractIoFilterChain.access$1100(AbstractIoFilterChain.java:53)
        at org.apache.mina.common.support.AbstractIoFilterChain$EntryImpl$1.messageReceived(AbstractIoFilterChain.java:648)
        at org.apache.mina.filter.executor.ExecutorFilter.processEvent(ExecutorFilter.java:220)
        at org.apache.mina.filter.executor.ExecutorFilter$ProcessEventsRunnable.run(ExecutorFilter.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:51)
        at java.lang.Thread.run(Unknown Source)
Failed to load character.

**Comment by Reeeeeemi** [comment]
Solved by add missing tables. Closed.
