### ISSUE TITLE
cannot launch .

### ISSUE THREAD

**Issue by z4q** [myowenthings/Nexus-v117#5]
➜  Nexus-v117 git:(master) ✗ java -jar bin/Nexus-v117.jar
Server Rates: Exp 5 / Meso 10 / Drop 2
[===========                                        ] 20% (Quests)Exception in thread "main" java.lang.ExceptionInInitializerError
	at server.Start.run(Unknown Source)
	at server.Start.main(Unknown Source)
Caused by: java.lang.NullPointerException
	at provider.MapleDataProvider.fillMapleDataEntitys(Unknown Source)
	at provider.MapleDataProvider.<init>(Unknown Source)
	at provider.MapleDataProviderFactory.getWZ(Unknown Source)
	at provider.MapleDataProviderFactory.getDataProvider(Unknown Source)
	at server.life.MapleLifeFactory.<clinit>(Unknown Source)
	... 2 more
➜  Nexus-v117 git:(master) ✗

**Comment by myowenthings** [comment]
I committed my wz folder. You need to extract the wz.tar.gz tar ball into the Nexus working directory.
